logging:
    severity: trace
    format: json
    file-path: smh/logs/log-2.json

cache-dir: smh/run/filecache-2

file-cache:
    max-size-mb: -1
    cache-file-for-range-read: true

metadata-cache:
    ttl-secs: -1

akeso:
    strategy: strawman
    akeso-dir: smh/akeso.d # ensure smh/akeso.d exists
    project-id: ornate-flame-397517

    setup-topic-id: atp-group-setup
    setup-sub-id: atp-group-setup-2
    update-topic-id: atp-key-update
    update-sub-id: atp-key-update-2

    key-file: key

    art: 
        index: 3
        member-name: 2
        group-name: eval

        # akeso.dir/group-name/member-name/keys
        initiator-pub-ik-file: initiator-pub-ik.pem
        member-ek-file: member-ek.pem

        # akeso.dir/group-name/member-name/setup
        setup-msg-file: setup-msg.json
        setup-msg-sig-file: setup-msg-sig.json
        
        # akeso.dir/group-name/member-name/update
        update-msg-file: update-msg.json
        update-msg-sig-file: update-msg-sig.json

        # akeso.dir/group-name/member-name
        tree-state-file: tree-state.json
        stage-key-file: stage-key.pem