logging:
    severity: trace
    format: json
    file-path: smh/logs/log.json

cache-dir: smh/run/filecache

file-cache:
    max-size-mb: -1
    cache-file-for-range-read: true

metadata-cache:
    ttl-secs: -1

akeso:
    setup-channel: GroupSetup
    update-channel: KeyUpdate
    strategy: strawman 
    project: ornate-flame-397517 
    akeso_dir: smh/akeso.d 
    member_name: bob